template_project/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

# TEMPLATE tagging
app_name = 'basic_app'

urlpatterns = [
    url(r'^register/$',views.registration,name="register"),
    url(r'^other/$',views.other,name="other"),
    url(r'^relative/$',views.relative,name="relative"),
    url(r'^user_login/$',views.user_login,name="user_login"),
]

template_project/template_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/',include('basic_app.urls')),
    url(r'^logout/$',views.user_logout,name="logout"),
    url(r'special/',views.special,name="special"),
]

template_project/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)
    portfolio = models.URLField(blank=True)
    picture = models.ImageField(upload_to="profile_pics", blank=True)

    def __str__(self):
        return self.user.username

template_project/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ['username','email','password']

class UserProfileForm(forms.ModelForm):
    # portfolio = forms.URLField(required=False)
    # picture = forms.ImageField(required=False)

    class Meta():
        model = UserProfileInfo
        fields = ['portfolio','picture']

template_project/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    # dicti = {'text':'hello world','number':100}
    return render(request,'basic_app/index.html')

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url.html')

def registration(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            # Check, if picture was sent with the form
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()

            registered = True

        else:
            print(user_form.errors(),profile_form.errors())
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request,'basic_app/registration.html',
                            {'user_form':user_form,
                             'profile_form': profile_form,
                             'registered':registered})

@login_required
def special(request):
    return HttpResponse("You are logged in!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account not active!')
        else:
            print('User: {} and pwd {} not active!'.format(username,password))
    else:
        return render(request,'basic_app/login.html')

template_project/templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" >
      <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="{% url 'admin:index' %}">Admin</a>
          <a class="nav-item nav-link" href="{% url 'basic_app:register'%}">Register</a>

          {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'logout'%}">Logout</a>
          {% else %}
            <a class="nav-item nav-link" href="{% url 'basic_app:user_login'%}">Log in</a>
          {% endif %}

        </div>
      </div>
    </nav>

    <div class="container">
      {% block body_block%}
      {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>

  </body>
</html>

template_project/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Django level Five! :)</h1>
    <!-- <h2>template inheritance!!!</h2>
    <h3>{{ text|cut:"ello" }}</h3>
    <h3>{{ number|add:"3" }}</h3> -->
  </div>
{% endblock %}

template_project/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% load staticfiles %}
{% block body_block %}

  <div class="jumbotron">
    <h1>Please login!</h1>
    <form action="{% url 'basic_app:user_login' %}" method="post">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" id="username" placeholder="Enter username">

      <label for="password">Password:</label>
      <input type="password" id="password">

      <input type="submit" name="" value="Login">
    </form>

  </div>
{% endblock %}

template_project/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
    <h1>WELCOME to OTHER</h1>
    <h2>template inheritance!!!</h2>
{% endblock %}

template_project/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="jumbotron">

    {% if registered %}
      <h1>Thank you for your registration</h1>
    {% else %}
      <h1>Register here!</h1>
      <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register">
      </form>
    {% endif %}
  </div>
{% endblock %}

template_project/templates/basic_app/relative_url.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>WELCOME to RELATIVE URL HTML</h1>
    <a href="{% url 'basic_app:other' %}">OTHER page</a>
    <a href="{% url 'admin:index' %}">ADMIN page</a>
  </body>
</html>